### ISSUE TITLE
Problem with non utf-8 or bad csv files

### ISSUE THREAD

**Issue by pachevalier** [opendatateam/udata-explorer#2]
As expected, it's really complex to have a generic function which works with all kind of files. For instance, `get_data` doesn't work with non utf-8 files. 

```
from udata_explorer.explorer import Explorer
import pandas as pd
# instantiate the explorer w/ a udata instance API url
explorer = Explorer('https://data.gouv.fr/api/1/')
dataset = explorer.get_dataset('5a9675b4c751df529aad26f2')
dataset.resources[0].get_data()

```
Very often, when browsing files from datagouv, I have to download the file, find the encoding using `file -i` or `chardetect`, convert the file to utf-8 using `iconv` and load the file in R or Python.

Do you know any solution for that ?

**Comment by abulte** [comment]
I tried something hackish there #3, feel free to try it out. It will try to detect the encoding, the delimiter and skip some rows at the beginning of the file if they make the parsing fail.

`pip install "git+https://github.com/opendatateam/udata-explorer.git@gh-#2-detect-encoding"`
